const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AJAX,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Behaviors.wrap,
		C3.Behaviors.Bullet,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Arr,
		C3.Plugins.Clipboard,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Browser.Exps.QueryParam,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.System.Cnds.IsPreview,
		C3.JavaScriptInEvents.轉_Event4_Act1,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.AdvancedRandom.Acts.CreatePermutationTable,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.AdvancedRandom.Acts.ShufflePermutationTable,
		C3.Plugins.AdvancedRandom.Exps.Permutation,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.Clipboard.Acts.CopyText,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Clipboard.Cnds.OnCopySuccess,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.CompareCurrent,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Audio.Cnds.IsTagPlaying
	];
};
self.C3_JsPropNameTable = [
	{AJAX: 0},
	{Browser: 0},
	{補間動畫: 0},
	{題幹: 0},
	{輸入顯示: 0},
	{Touch: 0},
	{密碼輸入: 0},
	{編號: 0},
	{邊界穿梭: 0},
	{子彈: 0},
	{正弦: 0},
	{思緒: 0},
	{音頻: 0},
	{選項字: 0},
	{背景: 0},
	{被按: 0},
	{對話框: 0},
	{文字: 0},
	{"4按鈕": 0},
	{選項: 0},
	{切換: 0},
	{身體: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{計時: 0},
	{按鈕內容: 0},
	{xx: 0},
	{yy: 0},
	{系統提示: 0},
	{高級隨機: 0},
	{答案陣列: 0},
	{出題: 0},
	{抽筋圈: 0},
	{Sprite5: 0},
	{生命: 0},
	{剪貼板: 0},
	{陰影: 0},
	{播放中: 0},
	{關卡: 0},
	{XX: 0},
	{YY: 0},
	{密碼: 0},
	{時間: 0},
	{成敗: 0},
	{輸入: 0},
	{間隔: 0},
	{動畫表: 0},
	{數字: 0},
	{極限: 0},
	{初次: 0},
	{第幾碼: 0},
	{血量: 0},
	{進退: 0},
	{監看: 0},
	{階段: 0}
];

self.InstanceType = {
	AJAX: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	題幹: class extends self.ITextInstance {},
	輸入顯示: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	密碼輸入: class extends self.ITextInstance {},
	思緒: class extends self.ITextInstance {},
	音頻: class extends self.IInstance {},
	選項字: class extends self.ITextInstance {},
	背景: class extends self.ISpriteInstance {},
	對話框: class extends self.ISpriteInstance {},
	_4按鈕: class extends self.ISpriteInstance {},
	選項: class extends self.ISpriteInstance {},
	身體: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	計時: class extends self.ITextInstance {},
	系統提示: class extends self.ITextInstance {},
	高級隨機: class extends self.IInstance {},
	答案陣列: class extends self.IArrayInstance {},
	出題: class extends self.IArrayInstance {},
	抽筋圈: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	生命: class extends self.ISpriteInstance {},
	剪貼板: class extends self.IInstance {},
	陰影: class extends self.ITextInstance {}
}